name: Welcome New Contributors

on:
  pull_request_target:
    types:
      - opened
      - synchronize
  issues:
    types:
      - opened

jobs:
  greet_contributors:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Check First Interaction
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Welcome to our repository! We're glad you're here. Please provide details about the issue you're facing or the contribution you'd like to make."
          pr-message: "Hello there! Thank you for your pull request. Please include a brief description of the changes you've made and any relevant context."
