name: ESLint

on:
  push:
    branches: [main] # Assuming main is your default branch
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0" # This will schedule the job every Sunday at midnight

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # You can adjust the version as needed

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint # Adjust the lint command as per your project setup
