name: Lint and Code Quality Check

on:
  push:
    branches:
      - main # change this to your default branch if it's not named 'main'
  pull_request:
    branches:
      - main # change this to your default branch if it's not named 'main'

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint './**/*.ts' --format=json --output-file=eslint.json

      - name: Upload ESLint results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: eslint.json
